#!/bin/bash

# this variable gets generated by the app itself
address="http://localhost:8000"
ansible_tar="$address/setup/ansible/"


curl -o ansible.tar.gz "$ansible_tar"
tar xzf ansible.tar.gz

bash build/bin/ansible --version
bash build/bin/ansible-playbook --version

# this needs to be pre-populated so that the script understands what it needs
# to ask from the app
curl -o playbook.tar.gz "$address/build/"
tar xzf playbook.tar.gz
cd playbook

# this may need to be templated out, since we are assuming the yml file
bash ../build/bin/ansible-playbook -i "localhost," -c local setup.yml
